Repository HabanaAI/pyhlml, pull requests merged in 2022-03, with the labels that each got.

#6 Included Python3.6
  pyproject.toml
  setup.cfg
Labels: size/XS

#9 Update pullrequest.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/M

#8 Fix _test_pyhlml_metrics.py syntax error.
  tests/_test_pyhlml_metrics.py
Labels: size/XS

#10 Fix for SW78342
  pyhlml/hlml_types.py
  pyhlml/main.py
  tests/test_pyhlml_attributes.py
  tests/test_pyhlml_metrics.py
Labels: size/L
